config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sign_out', to: 'sessions#sign_out'

  resources :tweets, only: [:create]
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :user_id, :body, presence: true

  before_create :post_to_twitter

  def post_to_twitter
    user.twitter.update(body)
  end

  def self.break_up(text)
    chunks_array = []
    if text.length <= 140
      chunks_array << text
    else

    end
  end
end


# tweet.body regex thing but not before (...)

app/models/user.rb
class User < ActiveRecord::Base
	def self.find_or_create_from_auth_hash(auth_hash)
		user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
		user.update(
			name: auth_hash.info.name,
			profile_image: auth_hash.info.image,
			token: auth_hash.credentials.token,
			secret: auth_hash.credentials.secret
			)
		user
	end

	def twitter
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['twitter_api_key']
      config.consumer_secret     = ENV['twitter_api_secret']
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tweet = Tweet.new

    if session[:user_id]
      @user = User.find(session[:user_id]) 
      @timeline_tweets = @user.twitter.user_timeline.first(5)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		@user = User.find_or_create_from_auth_hash(auth_hash)
		session[:user_id] = @user.id 
		redirect_to root_path
	end

  def sign_out
    session[:user_id] = nil 
    redirect_to root_path
  end

protected

	def auth_hash
		request.env['omniauth.auth']
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def create
    @user = current_user

    if tweet_params
      text = ChunkyText::Chunker.new(tweet_params[:body], 140)
    
      text.chunk_array.each do |tweet_text|
        tweet = Tweet.new(body: tweet_text, user_id: @user.id) 
        tweet.post_to_twitter
      end
      
      # add a modal for tweet timeline
      flash[:success] = "Your tweet(s) has been sent!"
      redirect_to root_path
    else
      flash[:error] = "The tweet can't be empty."
      render 'home/index'
    end
  end

  private

    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <div class="headline">
      <h2 class="tk-bebas-neue">Tweet Your Thoughts. <b>Make It Rain</b></h2>
    </div>
  </div>
  <div class="small-12 columns">
    <%= render "layouts/messages" %>
  </div> 
  <div class="small-12 columns message">
    <%= form_for @tweet do |f| %>
      <%= f.text_area :body, placeholder: 'Brella lets you type as much as you want, and then intelligently breaks it up into multiple tweets. You can tell a short story, or go on a rant. We’ll break it down for you, so you can keep typing, and tweeting without worrying if you’re going to go over the amount of space Twitter gives you.' 
      %>
      <%= f.submit "Send Tweets", class: "button submit expand tk-bebas-neue" %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="row foot clearfix">
  <div class="large-6 columns">
    <img src="/assets/Brella-1X.png" height="100%" width="200">
  </div>
  <div class="large-6 columns">
    <ul class="inline-list right">
      <li><a href="#">Contact</a></li>
      <li><a href="#">Terms Of Use</a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="top-bar " data-topbar role="navigation">
    <div class="row">
      <% if current_user %>  
        <div class="current_user">
          <%= "signed in as #{current_user.name}" %>
        </div>
      <% end %>
      <div class="small-8 columns">
          <%= image_tag("Brella-1X.png", class: "brella logo left") %>
      </div>
      <div class="small-4 columns">
        <% if current_user %>
          <%= link_to "Sign Out" , sign_out_path, class: "button login right" %>
        <% else %>
          <%= link_to "Sign In/Up" , '/auth/twitter', class: "button login right" %>
        <% end %>
	    </div>
    </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <br>
    <div data-alert class="alert-box <%= name %> radius">
       <%= msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Brella</title>

    <%= stylesheet_link_tag "application" %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <script src="//use.typekit.net/bzz0sek.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= javascript_include_tag "application" %>
  </body>
</html>